#!/usr/bin/env python3
"""Reset the examples/vampire/ scene to a clean, eval-ready state.

The vampire example is used as the live scene for LLM eval tasks. Eval runs
mutate it (create nodes, rename nodes, attach scripts, etc.). This script
restores main.tscn from git HEAD and removes any eval-created files in the
vampire project (scripts, scenes, resources generated by the harness).
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
VAMPIRE_DIR = REPO_ROOT / "examples" / "vampire"

# Patterns of eval-created files to remove within the vampire project
PATTERNS = [
    "tmp_e2e*",
    "eval_test*.gd",
    "eval_test*.gd.uid",
    "play_test.gd",
    "play_test.gd.uid",
    "char_test.gd",
    "char_test.gd.uid",
    "Batch*.tscn",
    "MutTest.tscn",
    "RenameMe.tscn",
    "CharTest.tscn",
    "Chain*.tscn",
]

# Directories to scan for eval artifacts
SEARCH_DIRS = [
    VAMPIRE_DIR,
    VAMPIRE_DIR / "scripts",
    VAMPIRE_DIR / "scenes",
    VAMPIRE_DIR / "shaders",
]


def remove_artifacts() -> int:
    removed = 0
    for directory in SEARCH_DIRS:
        if not directory.exists():
            continue
        for pattern in PATTERNS:
            for path in directory.glob(pattern):
                try:
                    if path.is_dir():
                        shutil.rmtree(path)
                    else:
                        path.unlink()
                    removed += 1
                    print(f"  Removed: {path.relative_to(REPO_ROOT)}")
                except OSError as exc:
                    print(f"  Failed to remove {path}: {exc}", file=sys.stderr)
    return removed


def git_restore() -> None:
    """Restore tracked files in examples/vampire/ from git HEAD."""
    print("Restoring tracked files in examples/vampire/ from git HEAD...")
    result = subprocess.run(
        ["git", "checkout", "HEAD", "--", "examples/vampire/"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print(f"git checkout warning: {result.stderr}", file=sys.stderr)
    else:
        print("  Tracked files restored.")


def clear_godot_cache() -> None:
    cache_dir = VAMPIRE_DIR / ".godot"
    if cache_dir.exists():
        shutil.rmtree(cache_dir)
        print(f"  Cleared: {cache_dir.relative_to(REPO_ROOT)}")


def main() -> int:
    print("Resetting examples/vampire/ project...")
    removed = remove_artifacts()
    git_restore()
    clear_godot_cache()
    if removed:
        print(f"Done. Removed {removed} eval artifact(s).")
    else:
        print("Done. No artifacts found.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
